2023-06-13 14:08:02,343 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:08:10,361 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:08:18,371 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:08:26,388 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:08:34,399 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:08:42,415 ERROR PID_25230 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/main-1.py", line 34, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 14:11:45,850 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:11:53,954 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:12:01,969 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:12:09,980 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:12:17,994 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:12:26,005 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:12:34,023 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:12:42,035 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:12:50,048 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:12:58,161 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:13:06,256 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:13:14,268 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:13:22,329 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:13:30,378 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:13:38,397 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:13:46,408 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:13:54,415 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:14:02,434 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:14:10,507 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:14:18,550 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:14:26,701 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:14:34,724 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:14:42,737 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:14:50,760 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:14:58,786 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:15:06,907 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:15:14,920 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:15:22,929 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:15:30,938 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:15:38,950 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:15:46,961 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:15:54,970 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:16:02,981 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:16:10,989 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:16:18,999 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:16:27,009 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:16:35,020 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:16:43,031 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:16:51,120 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:16:59,158 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:17:07,172 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:17:15,184 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:17:23,210 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:17:31,219 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:17:39,228 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:17:47,237 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:17:55,273 INFO PID_26722 Receive response from modbus server: 3
2023-06-13 14:18:03,381 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:18:11,479 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:18:19,533 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:18:27,641 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:18:35,668 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:18:43,766 INFO PID_26722 Receive response from modbus server: 5
2023-06-13 14:18:51,809 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:18:59,834 INFO PID_26722 Receive response from modbus server: 2
2023-06-13 14:19:07,844 INFO PID_26722 Receive response from modbus server: 4
2023-06-13 14:19:15,851 INFO PID_26722 Receive response from modbus server: 1
2023-06-13 14:19:20,911 INFO PID 29659 Start player
2023-06-13 14:19:20,923 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:19:28,938 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:19:36,947 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:19:44,956 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:19:52,965 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:20:00,974 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:20:08,984 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:20:16,995 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:20:25,006 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:20:33,058 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:20:41,071 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:20:49,082 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:20:57,092 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:21:05,104 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:21:13,111 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:21:21,120 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:21:29,129 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:21:37,140 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:21:45,149 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:21:53,160 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:22:01,172 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:22:09,183 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:22:17,192 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:22:25,203 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:22:33,213 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:22:41,224 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:22:49,234 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:22:57,245 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:23:05,253 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:23:13,262 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:23:21,271 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:23:29,283 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:23:37,292 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:23:45,301 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:23:53,310 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:24:01,319 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:24:09,327 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:24:17,336 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:24:25,345 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:24:33,354 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:24:41,363 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:24:49,374 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:24:57,383 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:25:05,397 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:25:13,407 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:25:21,416 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:25:29,426 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:25:37,439 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:25:45,457 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:25:53,466 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:26:01,483 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:26:09,493 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:26:17,503 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:26:25,512 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:26:33,521 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:26:41,533 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:26:49,542 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:26:57,551 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:27:05,559 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:27:13,569 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:27:21,583 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:27:29,594 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:27:37,604 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:27:45,614 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:27:53,625 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:28:01,640 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:28:09,647 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:28:17,655 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:28:25,667 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:28:33,676 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:28:41,683 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:28:49,693 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:28:57,703 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:29:05,712 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:29:13,720 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:29:21,729 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:29:29,737 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:29:37,748 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:29:45,758 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:29:53,770 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:30:01,781 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:30:09,791 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:30:17,804 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:30:25,813 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:30:33,822 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:30:41,831 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:30:49,842 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:30:57,850 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:31:05,862 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:31:13,874 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:31:21,883 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:31:29,894 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:31:37,905 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:31:45,913 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:31:53,924 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:32:01,933 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:32:09,945 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:32:17,956 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:32:25,967 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:32:33,976 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:32:41,986 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:32:49,995 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:32:58,007 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:33:06,016 INFO PID 29659 Receive response from modbus server: 4
2023-06-13 14:33:14,029 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:33:22,041 INFO PID 29659 Receive response from modbus server: 3
2023-06-13 14:33:30,052 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:33:38,064 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:33:46,073 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:33:54,083 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:34:02,095 INFO PID 29659 Receive response from modbus server: 1
2023-06-13 14:34:10,107 INFO PID 29659 Receive response from modbus server: 2
2023-06-13 14:34:18,122 INFO PID 29659 Receive response from modbus server: 5
2023-06-13 14:36:14,858 INFO PID 34708 Start player
2023-06-13 14:36:14,868 INFO PID 34708 Receive response from modbus server: 1
2023-06-13 14:36:22,878 INFO PID 34708 Receive response from modbus server: 3
2023-06-13 14:38:07,585 INFO PID 34965 Start player
2023-06-13 14:38:07,587 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:38:07,598 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:38:15,598 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:38:15,648 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:38:23,648 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:38:23,659 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:38:31,660 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:38:31,668 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:38:39,668 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:38:39,677 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:38:47,678 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:38:47,687 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:38:55,687 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:38:55,698 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:39:03,699 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:39:03,710 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:39:11,711 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:39:11,721 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:39:19,722 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:39:19,730 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:39:27,731 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:39:27,740 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:39:35,742 INFO PID 34965 Playing video file 1.mp4
2023-06-13 14:39:35,752 INFO PID 34965 Receive response from modbus server: 1
2023-06-13 14:39:43,752 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:39:43,765 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:39:51,765 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:39:51,773 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:39:59,773 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:39:59,783 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:40:07,784 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:40:07,791 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:40:15,792 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:40:15,799 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:40:23,800 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:40:23,810 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:40:31,811 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:40:31,820 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:40:39,821 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:40:39,828 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:40:47,829 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:40:47,837 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:40:55,837 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:40:55,845 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:41:03,846 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:41:03,860 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:41:11,861 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:41:11,870 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:41:19,871 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:41:19,884 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:41:27,885 INFO PID 34965 Playing video file 1.mp4
2023-06-13 14:41:27,893 INFO PID 34965 Receive response from modbus server: 1
2023-06-13 14:41:35,894 INFO PID 34965 Playing video file 1.mp4
2023-06-13 14:41:35,905 INFO PID 34965 Receive response from modbus server: 1
2023-06-13 14:41:43,906 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:41:43,918 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:41:51,919 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:41:51,928 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:41:59,929 INFO PID 34965 Playing video file 1.mp4
2023-06-13 14:41:59,938 INFO PID 34965 Receive response from modbus server: 1
2023-06-13 14:42:07,939 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:42:07,950 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:42:15,950 INFO PID 34965 Playing video file 4.mp4
2023-06-13 14:42:15,958 INFO PID 34965 Receive response from modbus server: 4
2023-06-13 14:42:23,958 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:42:23,969 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:42:31,969 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:42:31,979 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:42:39,980 INFO PID 34965 Playing video file 1.mp4
2023-06-13 14:42:39,990 INFO PID 34965 Receive response from modbus server: 1
2023-06-13 14:42:47,990 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:42:48,002 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:42:56,003 INFO PID 34965 Playing video file 2.mp4
2023-06-13 14:42:56,044 INFO PID 34965 Receive response from modbus server: 2
2023-06-13 14:43:04,044 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:43:04,057 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:43:12,057 INFO PID 34965 Playing video file 5.mp4
2023-06-13 14:43:12,070 INFO PID 34965 Receive response from modbus server: 5
2023-06-13 14:43:20,070 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:43:20,080 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 14:43:28,081 INFO PID 34965 Playing video file 3.mp4
2023-06-13 14:43:28,097 INFO PID 34965 Receive response from modbus server: 3
2023-06-13 23:36:00,907 INFO PID 2213 Start player
2023-06-13 23:36:00,920 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:36:00,972 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:08,984 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:36:09,045 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:17,048 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:36:17,072 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:25,083 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:36:25,127 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:33,136 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:36:33,178 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:41,184 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:36:41,213 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:49,224 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:36:49,277 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:36:57,288 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:36:57,341 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:05,348 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:37:05,394 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:13,404 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:37:13,445 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:21,452 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:37:21,485 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:29,496 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:37:29,535 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:37,544 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:37:37,604 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:45,616 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:37:45,671 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:37:53,684 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:37:53,739 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:01,748 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:38:01,796 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:09,805 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:38:09,853 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:17,860 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:38:17,897 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:25,911 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:38:25,997 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:34,012 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:38:34,073 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:42,084 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:38:42,121 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:50,129 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:38:50,192 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:38:58,200 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:38:58,282 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:06,292 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:39:06,350 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:14,356 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:39:14,383 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:22,392 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:39:22,431 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:30,444 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:39:30,505 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:38,516 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:39:38,647 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:46,668 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:39:46,752 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:39:54,760 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:39:54,813 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:02,824 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:40:02,899 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:10,908 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:40:11,066 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:19,075 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:40:19,095 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:27,104 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:40:27,140 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:35,148 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:40:35,172 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:43,182 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:40:43,204 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:51,212 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:40:51,239 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:40:59,248 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:40:59,274 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:07,284 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:41:07,307 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:15,317 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:41:15,359 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:23,369 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:41:23,398 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:31,408 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:41:31,446 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:39,456 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:41:39,484 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:47,494 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:41:47,519 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:41:55,528 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:41:55,560 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:03,568 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:42:03,602 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:11,612 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:42:11,639 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:19,648 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:42:19,693 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:27,704 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:42:27,733 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:35,740 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:42:35,775 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:43,784 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:42:43,819 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:51,828 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:42:51,859 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:42:59,868 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:42:59,891 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:07,900 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:43:07,932 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:15,940 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:43:15,962 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:23,972 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:43:23,996 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:32,004 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:43:32,023 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:40,031 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:43:40,054 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:48,064 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:43:48,083 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:43:56,092 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:43:56,112 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:04,124 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:44:04,146 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:12,156 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:44:12,184 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:20,195 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:44:20,226 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:28,236 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:44:28,268 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:36,276 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:44:36,310 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:44,320 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:44:44,338 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:44:52,348 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:44:52,369 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:00,380 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:45:00,412 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:08,424 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:45:08,449 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:16,460 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:45:16,492 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:24,500 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:45:24,527 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:32,538 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:45:32,559 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:40,568 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:45:40,607 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:48,616 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:45:48,644 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:45:56,652 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:45:56,681 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:04,688 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:46:04,721 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:12,728 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:46:12,755 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:20,764 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:46:20,793 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:28,803 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:46:28,823 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:36,832 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:46:36,862 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:44,872 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:46:44,902 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:46:52,912 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:46:52,943 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:00,952 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:47:00,973 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:08,985 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:47:09,025 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:17,032 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:47:17,056 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:25,065 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:47:25,097 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:33,108 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:47:33,139 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:41,150 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:47:41,184 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:49,195 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:47:49,215 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:47:57,225 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:47:57,254 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:05,263 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:48:05,292 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:13,300 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:48:13,324 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:21,331 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:48:21,355 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:29,363 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:48:29,386 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:37,396 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:48:37,428 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:45,436 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:48:45,483 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:48:53,491 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:48:53,525 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:01,537 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:49:01,569 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:09,579 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:49:09,611 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:17,621 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:49:17,658 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:25,667 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:49:25,689 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:33,695 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:49:33,717 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:41,724 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:49:41,764 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:49,772 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:49:49,794 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:49:57,803 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:49:57,822 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:05,832 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:50:05,865 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:13,872 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:50:13,898 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:21,908 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:50:21,941 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:29,949 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:50:29,989 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:38,000 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:50:38,022 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:46,032 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:50:46,068 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:50:54,080 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:50:54,104 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:02,112 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:51:02,144 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:10,154 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:51:10,175 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:18,185 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:51:18,206 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:26,215 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:51:26,240 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:34,248 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:51:34,273 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:42,283 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:51:42,324 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:50,332 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:51:50,378 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:51:58,390 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:51:58,422 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:06,432 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:52:06,455 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:14,464 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:52:14,489 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:22,500 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:52:22,523 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:30,532 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:52:30,563 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:38,572 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:52:38,610 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:46,619 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:52:46,642 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:52:54,652 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:52:54,697 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:02,704 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:53:02,728 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:10,735 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:53:10,767 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:18,776 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:53:18,807 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:26,816 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:53:26,843 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:34,852 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:53:34,890 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:42,899 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:53:42,931 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:50,943 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:53:50,965 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:53:58,976 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:53:59,001 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:07,008 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:54:07,038 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:15,049 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:54:15,071 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:23,080 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:54:23,109 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:31,116 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:54:31,146 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:39,156 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:54:39,182 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:47,192 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:54:47,223 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:54:55,232 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:54:55,268 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:03,275 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:55:03,313 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:11,326 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:55:11,369 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:19,380 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:55:19,406 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:27,417 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:55:27,442 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:35,452 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:55:35,475 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:43,485 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:55:43,516 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:51,526 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:55:51,566 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:55:59,576 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:55:59,596 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:07,604 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:56:07,632 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:15,640 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:56:15,674 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:23,684 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:56:23,711 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:31,720 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:56:31,754 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:39,765 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:56:39,804 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:47,816 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:56:47,853 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:56:55,860 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:56:55,891 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:03,900 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:57:03,936 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:11,943 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:57:11,983 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:19,991 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:57:20,015 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:28,024 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:57:28,058 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:36,067 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:57:36,098 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:44,108 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:57:44,142 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:57:52,154 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:57:52,176 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:00,184 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:58:00,214 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:08,224 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:58:08,256 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:16,264 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:58:16,289 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:24,299 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:58:24,324 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:32,334 INFO PID 2213 Playing video file 3.mp4
2023-06-13 23:58:32,356 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:40,367 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:58:40,416 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:48,423 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:58:48,450 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:58:56,464 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:58:56,501 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:04,512 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:59:04,548 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:12,560 INFO PID 2213 Playing video file 1.mp4
2023-06-13 23:59:12,585 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:20,597 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:59:20,620 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:28,628 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:59:28,649 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:36,659 INFO PID 2213 Playing video file 2.mp4
2023-06-13 23:59:36,722 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:44,734 INFO PID 2213 Playing video file 4.mp4
2023-06-13 23:59:44,766 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-13 23:59:52,776 INFO PID 2213 Playing video file 5.mp4
2023-06-13 23:59:52,805 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:00,813 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:00:00,852 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:08,863 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:00:08,889 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:16,900 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:00:16,934 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:24,943 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:00:24,966 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:32,976 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:00:33,045 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:41,060 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:00:41,084 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:49,091 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:00:49,115 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:00:57,124 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:00:57,149 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:05,159 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:01:05,191 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:13,200 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:01:13,221 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:21,233 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:01:21,267 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:29,275 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:01:29,307 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:37,316 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:01:37,345 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:45,351 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:01:45,375 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:01:53,384 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:01:53,417 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:01,425 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:02:01,454 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:09,464 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:02:09,502 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:17,512 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:02:17,535 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:25,544 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:02:25,568 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:33,580 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:02:33,621 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:41,629 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:02:41,669 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:49,676 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:02:49,715 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:02:57,719 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:02:57,748 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:05,756 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:03:05,788 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:13,800 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:03:13,834 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:21,844 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:03:21,870 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:29,880 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:03:29,937 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:37,948 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:03:37,982 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:45,992 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:03:46,028 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:03:54,036 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:03:54,089 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:02,095 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:04:02,116 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:10,123 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:04:10,143 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:18,152 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:04:18,191 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:26,206 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:04:26,244 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:34,254 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:04:34,292 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:42,300 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:04:42,322 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:50,332 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:04:50,370 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:04:58,380 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:04:58,414 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:06,423 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:05:06,445 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:14,452 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:05:14,471 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:22,479 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:05:22,515 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:30,524 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:05:30,555 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:38,564 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:05:38,595 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:46,603 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:05:46,643 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:05:54,651 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:05:54,675 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:02,684 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:06:02,706 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:10,714 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:06:10,737 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:18,744 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:06:18,775 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:26,784 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:06:26,806 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:34,816 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:06:34,850 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:42,860 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:06:42,896 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:50,908 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:06:50,933 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:06:58,940 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:06:58,971 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:06,980 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:07:07,019 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:15,028 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:07:15,090 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:23,100 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:07:23,120 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:31,129 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:07:31,158 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:39,168 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:07:39,202 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:47,212 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:07:47,256 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:07:55,264 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:07:55,287 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:03,296 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:08:03,331 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:11,340 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:08:11,365 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:19,373 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:08:19,408 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:27,416 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:08:27,450 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:35,460 INFO PID 2213 Playing video file 1.mp4
